name: smuxi
base: core18 # the base snap is the execution environment for this snap
version: '1.0.99.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: User-friendly and free IRC client for Linux, Windows and macOS
description: |
  Smuxi is a user-friendly and free IRC client for Linux, Windows and
  macOS, based on GNOME / GTK+
license: GPL-2.0

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

layout:
  /usr/share/.mono:
    symlink: $SNAP/etc/mono/certstore

apps:
  smuxi:
    command: bin/smuxi-frontend-stfl
    plugs: [network]

parts:
  smuxi:
    plugin: dump
    source: ./staging
    stage-packages:
      - mono-devel
      - liblog4net1.2-cil

  certs:
    plugin: dump
    source: /etc/mono
    organize:
      certstore: etc/mono/certstore

